# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count number of lines
#'
#' @param filename Path to the file.
#'
#' @export
#'
nlines <- function(filename) {
    .Call(`_bigreadr_nlines`, filename)
}

