# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlines_cpp <- function(file) {
    .Call(`_bigreadr_nlines_cpp`, file)
}

split_every_nlines <- function(name_in, prefix_out, every_nlines, repeat_header) {
    .Call(`_bigreadr_split_every_nlines`, name_in, prefix_out, every_nlines, repeat_header)
}

