# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Number of lines
#'
#' Get the number of lines of a file.
#'
#' @param file Path of the file.
#'
#' @return The number of lines as one integer.
#' @export
#'
#' @examples
#' tmp <- fwrite2(iris)
#' nlines(tmp)
#'
nlines <- function(file) {
    .Call(`_bigreadr_nlines`, file)
}

split_every_nlines <- function(name_in, prefix_out, every_nlines, repeat_header) {
    .Call(`_bigreadr_split_every_nlines`, name_in, prefix_out, every_nlines, repeat_header)
}

